/**
 * http://docs.oracle.com/javase/tutorial/uiswing/painting/step3.html
 */

package edu.plu.cs.views;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.MouseEvent;

/**
 *
 * @author PLUCSCE
 */
public class GamePanel extends javax.swing.JPanel {

    int initX = 20;
    int initY = 20;
    int WIDTH = 530;
    int HEIGHT = 530;
    int SIZE = 10;
    int selectedX;
    int selectedY;
    Color woodColor = new Color(150, 82, 45);
    
    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
        setPreferredSize(new Dimension(880, 600));
        
    }

    /**
     * The paint component draws the board and alternates
     * the color
     * @param g 
     */
    @Override
    protected void paintComponent(Graphics g) 
    {
        super.paintComponent(g);
        for(int i = 0; i<SIZE; i++)
        {
            for(int j = 0; j<SIZE; j++)
            {   
                g.setColor(woodColor);
                g.fillRect(initX+(i*(WIDTH/SIZE)), initY+(j*(WIDTH/SIZE)),WIDTH/SIZE,HEIGHT/SIZE);
                g.setColor(Color.BLACK);
                g.drawRect(initX+(i*(WIDTH/SIZE)),initY+(j*(WIDTH/SIZE)),WIDTH/SIZE,HEIGHT/SIZE);
            }
                //This bit of code is the logic to check the location of the click and add a piece
                /*if(selectedX<=(100+(i*(WIDTH/5))) && selectedX>=(i*(WIDTH/5)) &&
                        selectedY<=(100+(j*(WIDTH/5))) && selectedY>=((j*(WIDTH/5))))
                {
                    g.setColor(Color.WHITE);
                    g.fillOval(initX+(i*(WIDTH/5)), initY+(j*(WIDTH/5)),WIDTH/5,HEIGHT/5);
                    
                }*/
        }
        g.drawRect(initX+1, initY+1, WIDTH-2, HEIGHT-2);
        g.drawRect(initX+2, initY+2, WIDTH-4, HEIGHT-4);
    }
    
    /**
     * The mousePressed method waits for the mouse to be pressed,
     * sets the location values based on the location of the click,
     * and calls the repaint method.
     * @param e 
     * THIS METHOD DOES NOT WORK
     */
    public void mousePressed(MouseEvent e) 
    {
        selectedX = e.getX();
        selectedY = e.getY();
        repaint();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chatTA = new javax.swing.JTextArea();
        chatTF = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        Surrender = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(880, 600));
        setMinimumSize(new java.awt.Dimension(880, 600));
        setPreferredSize(new java.awt.Dimension(880, 600));

        chatTA.setEditable(false);
        chatTA.setColumns(20);
        chatTA.setRows(5);
        chatTA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(chatTA);

        chatTF.setBorder(null);

        sendButton.setText("Send");

        Surrender.setText("Surrender");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Surrender, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 470, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chatTF)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Surrender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Surrender;
    private javax.swing.JTextArea chatTA;
    private javax.swing.JTextField chatTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
