/*
 * The MIT License
 *
 * Copyright 2015 PLUCSCE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package gameplay.views;

import gameplay.GameView;
import java.awt.Color;
import java.awt.Cursor;
import static java.awt.Cursor.DEFAULT_CURSOR;

/**
 *
 * @author PLUCSCE
 */
public class BoardCell extends javax.swing.JPanel {
    
    private GameView parent;
    
    private boolean occupied;
    private boolean scrollOver;
    private boolean selected;
    
    private Color myColor;
    
    private int column;
    private int row;
    
    public BoardCell(){
        initComponents();
    }

    /**
     * Creates new form BoardCell
     * @param parent
     * @param row
     * @param column
     */
    public BoardCell(GameView parent, int row, int column) {  // So that means we are formatting like this: array[row][column]
        this.parent = parent;
        this.column = column;
        this.row = row;
        initComponents();
        myColor = gameButton.getBackground();
        occupied = false;
    }
    
    /**
     * sets this BoardCell as the selected cell in the Board
     */
    private void select(){
        selected = true;
        parent.selectedCell(this);
        gameButton.setBackground(Color.yellow);
    }
    
    /**
     * removes this BoardCell as the selected cell in the Board
     */
    public void unselect(){
        selected = false;
        gameButton.setBackground(myColor);
    }
    
    
    /**
     * sets this BoardCell to a specific player denoted by a color
     * disables the button  
     * @param youPlayed if true you played, else opponent played
     */
    public void playMove(boolean youPlayed){
        gameButton.setCursor(new Cursor(DEFAULT_CURSOR));
        gameButton.setEnabled(false);
        if( youPlayed ) {
            setGreen();
        }else{
            setRed();
        }
        occupied = true;
    }
    
    /**
     * returns the row that this is in
     * @return this row
     */
    public int getRow(){
        return row;
    }
    
    /**
     * returns the column that this is in
     * @return this column
     */
    public int getColumn(){
        return column;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 0, 102), new java.awt.Color(0, 204, 204)));
        setMaximumSize(new java.awt.Dimension(30, 30));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setName("basePanel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(20, 20));

        gameButton.setBackground(new java.awt.Color(102, 102, 102));
        gameButton.setForeground(new java.awt.Color(102, 102, 102));
        gameButton.setAutoscrolls(true);
        gameButton.setBorder(null);
        gameButton.setBorderPainted(false);
        gameButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gameButton.setMaximumSize(new java.awt.Dimension(30, 30));
        gameButton.setMinimumSize(new java.awt.Dimension(10, 10));
        gameButton.setPreferredSize(new java.awt.Dimension(20, 20));
        gameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseOverIn(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseOverOut(evt);
            }
        });
        gameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameButtonActionPerformed
        select();
    }//GEN-LAST:event_gameButtonActionPerformed
    
    /**
     * If this cell has not been selected, changes background
     * color when mouse is over
     * @param evt 
     */
    private void mouseOverIn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseOverIn
        if(!occupied && !selected){
            gameButton.setBackground(new Color(229,204,255));
            scrollOver = true;
        }
            
    }//GEN-LAST:event_mouseOverIn
    
    /**
     * If this cell's color has been changed due to a MouseOver,
     * this changes the color back.
     * @param evt 
     */
    private void mouseOverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseOverOut
        if(scrollOver && !selected){
            scrollOver = false;
            unselect();
        }
    }//GEN-LAST:event_mouseOverOut
    
    /**
     * Darkens this square to its original color and sets its to not enabled
     */
    public void darken(){
        unselect();
        occupied = true;
        scrollOver = false;
        gameButton.setEnabled(false);
        gameButton.setBackground(new Color(0,51,102));
    }
    
    /**
     * Changes this color to green
     */
    public void setGreen(){
        gameButton.setBackground(new Color(0,255,128));
    }
    
    /**
     * Changes this color to red
     */
    public void setRed(){
        gameButton.setBackground(new Color(255, 0, 107));
    }
    
    public void setYellow(){
        gameButton.setBackground(Color.yellow);
    }
    
    public void setWhite(){
        gameButton.setBackground(new Color(250,250,250));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gameButton;
    // End of variables declaration//GEN-END:variables
}
