

package gameplay.views;

import gameplay.GameController;

/**
 *
 * @author Joe
 */
public class victoryFrame extends javax.swing.JInternalFrame {

    
    private GameController controller;
    
    /** Creates new form victoryFrame */
    public victoryFrame(GameController controller, String results) {
        this.controller = controller;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        victoryLabel = new javax.swing.JLabel();
        playAgainLabel = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        victoryLabel.setFont(new java.awt.Font("Eras Demi ITC", 0, 48)); // NOI18N
        victoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        victoryLabel.setText("victoryLabel");

        playAgainLabel.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        playAgainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playAgainLabel.setText("Play again?");
        playAgainLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        yesButton.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        yesButton.setText("SURE");

        jButton2.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jButton2.setText("NOPE");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(playAgainLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(victoryLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(yesButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton2)
                        .add(22, 22, 22)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(victoryLabel)
                .add(18, 18, 18)
                .add(playAgainLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(yesButton)
                    .add(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel playAgainLabel;
    private javax.swing.JLabel victoryLabel;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables

}
