package client.views.lobby;

import gameplay.GameView;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PLUCSCE
 */
public class LobbyView extends javax.swing.JFrame {
    
    private final LobbyController controller;
    private String[] onlinePlayers;
    private String username;
    

    /**
     * Creates new form GameLobby
     * @param username
     * @param ctrl
     */
    public LobbyView(String username, LobbyController ctrl) {
        onlinePlayers = new String[100];
        this.username = username;
        controller = ctrl;
        initComponents();
        this.setTitle("Prometheus Client Interface");
        usernameLabel.setText(username);
    }

    /**
     * Updates the list of online players within the view
     * @param players 
     */
    public void updatePlayers(String[] players){
        DefaultListModel listModel = new DefaultListModel();
        for(int i=0; i<players.length; i++){
            if(!players[i].equals(username))
                listModel.addElement(players[i]);
        }
        onlinePlayersList.setModel(listModel);    
    }
    
    public void updateMyRecords(int wins, int gamesPlayed){
        gamesPlayedLabel.setText(gamesPlayed+"");
        winsLabel.setText(wins+"");
    }
    
    public void addGameView(String opName, GameView newGame){
        gameInterfacePanel.addTab(opName, newGame);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JLayeredPane();
        optionInterfacePanel = new javax.swing.JPanel();
        challengeButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        onlinePlayersList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        updatePanel = new javax.swing.JPanel();
        gamesPlayedTextLabel = new javax.swing.JLabel();
        winsTextLabel = new javax.swing.JLabel();
        winsLabel = new javax.swing.JLabel();
        gamesPlayedLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        gameInterfacePanel = new javax.swing.JTabbedPane();
        onlineLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(100, 180, 240));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setName("lobbyView"); // NOI18N
        setResizable(false);

        basePanel.setBackground(new java.awt.Color(40, 160, 220));
        basePanel.setFocusable(false);
        basePanel.setMaximumSize(new java.awt.Dimension(1100, 700));
        basePanel.setMinimumSize(new java.awt.Dimension(1100, 700));
        basePanel.setOpaque(true);

        optionInterfacePanel.setBackground(new java.awt.Color(62, 98, 151));
        optionInterfacePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        optionInterfacePanel.setToolTipText("");
        optionInterfacePanel.setFocusable(false);
        optionInterfacePanel.setMaximumSize(new java.awt.Dimension(200, 600));
        optionInterfacePanel.setMinimumSize(new java.awt.Dimension(200, 600));
        optionInterfacePanel.setPreferredSize(new java.awt.Dimension(250, 600));

        challengeButton.setBackground(new java.awt.Color(51, 51, 51));
        challengeButton.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        challengeButton.setForeground(new java.awt.Color(204, 0, 51));
        challengeButton.setText("Challenge");
        challengeButton.setBorderPainted(false);
        challengeButton.setPreferredSize(new java.awt.Dimension(79, 177));
        challengeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                challengeButtonActionListener(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(102, 102, 102));
        logoutButton.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.setBorderPainted(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        onlinePlayersList.setBackground(new java.awt.Color(240, 240, 240));
        onlinePlayersList.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        onlinePlayersList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = onlinePlayers;
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(onlinePlayersList);
        onlinePlayersList.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("~ online ~");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jLabel1.setFocusable(false);
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 227, 227));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Who is");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setFocusable(false);

        updatePanel.setOpaque(false);

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        gamesPlayedTextLabel.setFont(new java.awt.Font("Magneto", 1, 16)); // NOI18N
        gamesPlayedTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        gamesPlayedTextLabel.setText("Total Played :");

        winsTextLabel.setFont(new java.awt.Font("Magneto", 0, 16)); // NOI18N
        winsTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        winsTextLabel.setText("Games Won :");

        winsLabel.setFont(new java.awt.Font("Magneto", 0, 14)); // NOI18N
        winsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        winsLabel.setText("0");

        gamesPlayedLabel.setFont(new java.awt.Font("Magneto", 0, 14)); // NOI18N
        gamesPlayedLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gamesPlayedLabel.setText("0");

        javax.swing.GroupLayout optionInterfacePanelLayout = new javax.swing.GroupLayout(optionInterfacePanel);
        optionInterfacePanel.setLayout(optionInterfacePanelLayout);
        optionInterfacePanelLayout.setHorizontalGroup(
            optionInterfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(optionInterfacePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionInterfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(challengeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(optionInterfacePanelLayout.createSequentialGroup()
                        .addGroup(optionInterfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gamesPlayedTextLabel)
                            .addComponent(winsTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(optionInterfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(winsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gamesPlayedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        optionInterfacePanelLayout.setVerticalGroup(
            optionInterfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionInterfacePanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(optionInterfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winsTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(winsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionInterfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gamesPlayedTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gamesPlayedLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(challengeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(updatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton)
                .addContainerGap())
        );

        challengeButton.getAccessibleContext().setAccessibleDescription("");

        usernameLabel.setBackground(new java.awt.Color(62, 98, 151));
        usernameLabel.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("username");
        usernameLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        usernameLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 4, true));
        usernameLabel.setFocusable(false);
        usernameLabel.setOpaque(true);

        titleLabel.setBackground(new java.awt.Color(100, 180, 240));
        titleLabel.setFont(new java.awt.Font("Magneto", 1, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Prometheus Game Lobby");
        titleLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titleLabel.setFocusable(false);
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        gameInterfacePanel.setBackground(new java.awt.Color(255, 255, 255));
        gameInterfacePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 4, true));
        gameInterfacePanel.setFocusable(false);
        gameInterfacePanel.setMaximumSize(new java.awt.Dimension(970, 690));
        gameInterfacePanel.setMinimumSize(new java.awt.Dimension(970, 690));
        gameInterfacePanel.setName(""); // NOI18N
        gameInterfacePanel.setPreferredSize(new java.awt.Dimension(970, 690));

        onlineLabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        onlineLabel.setForeground(new java.awt.Color(40, 255, 40));
        onlineLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        onlineLabel.setText("is ONLINE");
        onlineLabel.setFocusable(false);

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optionInterfacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(onlineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameInterfacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(onlineLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addComponent(optionInterfacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(gameInterfacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)))
        );
        basePanel.setLayer(optionInterfacePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        basePanel.setLayer(usernameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        basePanel.setLayer(titleLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        basePanel.setLayer(gameInterfacePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        basePanel.setLayer(onlineLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(basePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Reject Frame
     * 
     * @param opName
     */
    public void rejectFrame(String opName){
        RejectionFrame rejection = new RejectionFrame(controller,opName);
        updatePanel.add(rejection);
        rejection.setVisible(true);
    }
    
    /**
     * Not Online Frame
     * 
     * @param opName
     */
    public void notOnlineFrame(String opName){
        NotOnlineFrame notFound = new NotOnlineFrame(controller,opName);
        updatePanel.add(notFound);
        notFound.setVisible(true);
    }
    
    public void challengeFrame(String opName){
        RequestFrame challenge = new RequestFrame(controller,opName);
        updatePanel.add(challenge);
        challenge.setVisible(true);
    }
    
    public void leaderboardFrame(){
        LeaderboardFrame leaderboard=new LeaderboardFrame(controller);
        updatePanel.add(leaderboard);
        leaderboard.setVisible(true);
        
    }
    
    public void updateLeaderboard(String[] leaders){
        LeaderboardFrame leaderboard=new LeaderboardFrame(controller);
        updatePanel.add(leaderboard);
        leaderboard.setVisible(true);
        
        for(int i=0;i<leaders.length;i++){
            leaderboard.update(leaders[i]+"\n");
        }
    }
            
    /**
     * CHALLENGE
     * Sends a challenge from this client to the client with the selected username
     * @param evt 
     */
    private void challengeButtonActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_challengeButtonActionListener
        if(onlinePlayersList.isSelectionEmpty())
            return;
        String challengerName = ""+onlinePlayersList.getSelectedValue();
        controller.challenge(challengerName);
    }//GEN-LAST:event_challengeButtonActionListener

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        controller.logout();
        System.gc();
    }//GEN-LAST:event_logoutButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane basePanel;
    private javax.swing.JButton challengeButton;
    private javax.swing.JTabbedPane gameInterfacePanel;
    private javax.swing.JLabel gamesPlayedLabel;
    private javax.swing.JLabel gamesPlayedTextLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel onlineLabel;
    private javax.swing.JList onlinePlayersList;
    private javax.swing.JPanel optionInterfacePanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel winsLabel;
    private javax.swing.JLabel winsTextLabel;
    // End of variables declaration//GEN-END:variables
}
