/*
 * The MIT License
 *
 * Copyright 2015 Timothy Ernst.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package client.views.lobby;

/**
 *
 * @author Timothy Ernst
 */
public class RequestFrame extends javax.swing.JInternalFrame {

    private LobbyController controller;
    private String opName;
    /**
     * Creates new form matchmakingMessenger
     */
    public RequestFrame(LobbyController controller, String opName) {
        this.controller = controller;
        initComponents();
        this.opName = opName;
        opNameLabel.setText(opName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JLayeredPane();
        opNameLabel = new javax.swing.JLabel();
        statement1Label = new javax.swing.JLabel();
        statement2Label = new javax.swing.JLabel();
        acceptButton = new javax.swing.JButton();
        rejectButton = new javax.swing.JButton();

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Incoming Challenge!");

        backgroundPanel.setBackground(new java.awt.Color(102, 0, 102));
        backgroundPanel.setOpaque(true);

        opNameLabel.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        opNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        opNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        opNameLabel.setText("opName");

        statement1Label.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        statement1Label.setForeground(new java.awt.Color(204, 204, 204));
        statement1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statement1Label.setText("Challenge");

        statement2Label.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        statement2Label.setForeground(new java.awt.Color(204, 204, 204));
        statement2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statement2Label.setText("Received From :");

        acceptButton.setBackground(new java.awt.Color(200, 255, 200));
        acceptButton.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        acceptButton.setForeground(new java.awt.Color(102, 102, 102));
        acceptButton.setText("Accept");
        acceptButton.setBorderPainted(false);
        acceptButton.setOpaque(true);
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        rejectButton.setBackground(new java.awt.Color(255, 200, 200));
        rejectButton.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        rejectButton.setForeground(new java.awt.Color(102, 102, 102));
        rejectButton.setText("Reject");
        rejectButton.setBorderPainted(false);
        rejectButton.setOpaque(true);
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statement1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(opNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statement2Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addComponent(acceptButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statement1Label)
                .addGap(7, 7, 7)
                .addComponent(statement2Label)
                .addGap(1, 1, 1)
                .addComponent(opNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(acceptButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(rejectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        backgroundPanel.setLayer(opNameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundPanel.setLayer(statement1Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundPanel.setLayer(statement2Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundPanel.setLayer(acceptButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundPanel.setLayer(rejectButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        controller.acceptChallenge(opName);
        dispose();
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        controller.rejectChallenge(opName);
        dispose();
    }//GEN-LAST:event_rejectButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JLayeredPane backgroundPanel;
    private javax.swing.JLabel opNameLabel;
    private javax.swing.JButton rejectButton;
    private javax.swing.JLabel statement1Label;
    private javax.swing.JLabel statement2Label;
    // End of variables declaration//GEN-END:variables
}
